//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace researchDataBrowsingInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class biao
    {
        public string StudyInstanceUID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientSex { get; set; }
        public string PatientAge { get; set; }
        public string FilePath { get; set; }
        public string OperatorsName { get; set; }
        public string PatientBirthDate { get; set; }
        public string AccessionNumber { get; set; }
        public string StudyID { get; set; }
        public string BodyPartExamined { get; set; }
        public string StudyDate { get; set; }
        public string StudyTime { get; set; }
        public string Modality { get; set; }
        public string StudyDescription { get; set; }
    }
}
