//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace researchDataBrowsingInformationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<biao> biao { get; set; }
        public virtual DbSet<checkinfo> checkinfo { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<project_manager> project_manager { get; set; }
        public virtual DbSet<project_researcher> project_researcher { get; set; }
        public virtual DbSet<roleinfo> roleinfo { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
